### ISSUE TITLE
Test Scaffold Bug - Nest could not find DataSource element

### ISSUE THREAD

**Issue by andyslack** [juicyllama/framework#37]
When running tests (in client projects but maybe also in framework) I often see: 

``` Nest could not find DataSource element (this provider does not exist in the current context) {}
      at Logger.warn (node_modules/.pnpm/@juicyllama+utils@0.0.107/node_modules/@juicyllama/utils/src/utils/Logger.ts:53:12)
      at Scaffold.<anonymous> (node_modules/.pnpm/@juicyllama+core@0.0.315_@bugsnag+core@7.19.0_@swc+core@1.3.89_express@4.18.2_rxjs@7.8.1_yargs@17.7.2/node_modules/@juicyllama/core/src/test/scaffold.ts:126:11)
          at Generator.throw (<anonymous>)
      at rejected (node_modules/.pnpm/@juicyllama+core@0.0.315_@bugsnag+core@7.19.0_@swc+core@1.3.89_express@4.18.2_rxjs@7.8.1_yargs@17.7.2/node_modules/@juicyllama/core/dist/test/scaffold.js:6:65)```

Looks like something needs fixing in the scaffolding (maybe the closing down but not sure).

**Comment by yossi-shasho** [comment]
@andyslack fixed. the issue was that Typeorm's init lacked reference names to use later for closing the resource. I committed the directly to `main` as I saw no danger in the code. it ended up being a rather small fix.
