### ISSUE TITLE
TypeORM Issue

### ISSUE THREAD

**Issue by andyslack** [juicyllama/framework#70]
TypeORM gets broken when https://github.com/juicyllama/client-quickstart/ is linked to the framework for local development  via
```sh
pnpm run install:client:backend
```

the error is:

```
TypeORMError: Entity metadata for Animal#owner was not found. Check if you specified a correct entity object and if it's connected in the connection options.
```

**Comment by Yurko-Fedoriv** [comment]
@andyslack This seems to be the same symptom as #69 
quick fix (from within client-quickstart/backend, assuming framework is located in the same parent directory as client-quickstart):

```sh
> $ cd node_modules/@nestjs/
> $ rm -rf typeorm
> $ ln -s ../../../../framework/node_modules/@nestjs/typeorm
```

I expect that the fix developed for #69 will be suitable here too.

**Comment by Yurko-Fedoriv** [comment]
As a side note, importing required TypeOrm models [here](https://github.com/juicyllama/client-quickstart/blob/c09ee08e6f642f3c2fa76d13a1a91742f1f99c74/backend/src/modules/animals/animals.module.ts#L19) helps too, but it is far from being clean.

Mentioning this to potentially help community pinpoint similar issues.

**Comment by andyslack** [comment]
Fixed

**Comment by andyslack** [comment]
Hi @Yurko-Fedoriv 

We have an issue with Typeorm migrations with this new setup.

You can see this in the `client-quickstart` if you do the following:

1. Comment out: `MYSQL_SYNC=true # Automatically sync entities with database (in development only)` from the `.env` file.
2. Delete the tables in the local database
3. Run the command: `pnpm run migration:generate` from the `/backend` folder

You will get an error like: 

```
TypeORMError: Entity metadata for Animal#owner was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at /Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:720:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeInverseProperties (/Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:713:34)
    at /Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:84:58
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:84:25)
    at ConnectionMetadataBuilder.buildEntityMetadatas (/Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:66:150)
    at async DataSource.buildMetadatas (/Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/data-source/DataSource.js:460:33)
    at async DataSource.initialize (/Users/andrewslack/Sites/JuicyLlama/framework/node_modules/typeorm/data-source/DataSource.js:141:13)
    at async Object.handler (/Users/andrewslack/Sites/JuicyLlama/clients/quickstart/backend/node_modules/typeorm/commands/MigrationGenerateCommand.js:75:13)
```

The issue here is that the migration is expecting to load in entities from the framework as per the framework config:

https://github.com/juicyllama/framework/blob/main/backend/core/src/configs/database.config.ts#L20-L21

However my guess is that it's not finding the entites from  `path.resolve(process.cwd(), 'node_modules', '@juicyllama', '**', '*.entity.{js,ts}'),` as it's a symlink?

Any thoughts on how we can resolve this?

**Comment by andyslack** [comment]
This is now fixed :)
